// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3QNH423X8laQABoiS5vayP9shOsuy9E',
    appId: '1:932927090460:web:60193288194e5c22b414d9',
    messagingSenderId: '932927090460',
    projectId: 'sampark-chat-app-ef498',
    authDomain: 'sampark-chat-app-ef498.firebaseapp.com',
    storageBucket: 'sampark-chat-app-ef498.appspot.com',
    measurementId: 'G-33HJR3DQ17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dE3wnJWQAQQs820DnYVuTZejMVqlRCo',
    appId: '1:932927090460:android:7247c43bb19410eab414d9',
    messagingSenderId: '932927090460',
    projectId: 'sampark-chat-app-ef498',
    storageBucket: 'sampark-chat-app-ef498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIdGfB8f63trCc6UdomKbi9A8oBHLRp-g',
    appId: '1:932927090460:ios:d5f11aca7067cc46b414d9',
    messagingSenderId: '932927090460',
    projectId: 'sampark-chat-app-ef498',
    storageBucket: 'sampark-chat-app-ef498.appspot.com',
    iosBundleId: 'com.example.chatapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIdGfB8f63trCc6UdomKbi9A8oBHLRp-g',
    appId: '1:932927090460:ios:d5f11aca7067cc46b414d9',
    messagingSenderId: '932927090460',
    projectId: 'sampark-chat-app-ef498',
    storageBucket: 'sampark-chat-app-ef498.appspot.com',
    iosBundleId: 'com.example.chatapp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn3QNH423X8laQABoiS5vayP9shOsuy9E',
    appId: '1:932927090460:web:7d22366da8ade1ecb414d9',
    messagingSenderId: '932927090460',
    projectId: 'sampark-chat-app-ef498',
    authDomain: 'sampark-chat-app-ef498.firebaseapp.com',
    storageBucket: 'sampark-chat-app-ef498.appspot.com',
    measurementId: 'G-VGLQTE64DP',
  );
}
